CREATE OR REPLACE PROCEDURE P_ETL_CUST AS
CURSOR EXT_CUR_CUST IS
SELECT * FROM T_EXT_CUST;
EXT_ROW EXT_CUR_CUST%ROWTYPE;

BEGIN

FOR EXT_ROW IN EXT_CUR_CUST LOOP

INSERT INTO T_MT_CUSTOMER
VALUES
(
SYS_GUID(),
EXT_ROW.NAME,
EXT_ROW.DOB,
EXT_ROW.ADDRESS,
EXT_ROW.PHONE,
EXT_ROW.EMAIL,
EXT_ROW.MEMBERSHIP_PERIOD,
EXT_ROW.JOIN_DATE,
EXT_ROW.USERNAME,
EXT_ROW.CPASSWORD,
EXT_ROW.CODE
);


END LOOP;
COMMIT;
END;