CREATE OR REPLACE PROCEDURE P_ETL_STATIO AS
CURSOR EXT_CUR_STATIO IS 
SELECT extstatio.*, mtstatiotype.ID as TYPEID 
FROM T_EXT_STATIO extstatio
LEFT JOIN T_MT_STTYPE mtstatiotype on extstatio.typecode = mtstatiotype.CD;
EXT_ROW EXT_CUR_STATIO%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_STATIO LOOP

	INSERT INTO T_MT_STATIO 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.TYPEID, 
		EXT_ROW.PRICE, 
		EXT_ROW.STOCK,
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_STATIO;