CREATE OR REPLACE PROCEDURE P_ETL_BKTYPE AS
CURSOR EXT_CUR_BKTYPE IS 
SELECT * FROM T_EXT_BKTYPE;
EXT_ROW EXT_CUR_BKTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_BKTYPE LOOP

	INSERT INTO T_MT_BKTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_BKTYPE;