CREATE OR REPLACE PROCEDURE P_ETL_TRANTYPE AS
CURSOR EXT_CUR_TRANTYPE IS 
SELECT * FROM T_EXT_TRANTYPE;
EXT_ROW EXT_CUR_TRANTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_TRANTYPE LOOP

	INSERT INTO T_MT_TRANTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME,
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_TRANTYPE;