CREATE OR REPLACE PROCEDURE P_ETL_PUBLI AS
CURSOR EXT_CUR_PUBLI IS
SELECT EXPUBLI.*, MTPUBLI.ID AS MTPUBLIID 
FROM T_EXT_PUBLI EXPUBLI
LEFT JOIN T_MT_PUBLI MTPUBLI
ON EXPUBLI.CODE = MTPUBLI.CD;

EXT_ROW EXT_CUR_PUBLI%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_PUBLI LOOP

	IF EXT_ROW.MTPUBLIID IS NULL THEN
	INSERT INTO T_MT_PUBLI 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.ADDRESS, 
		EXT_ROW.PHONE, 
		EXT_ROW.EMAIL,
		EXT_ROW.WEBSITE,
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_PUBLI
	SET NAME = EXT_ROW.NAME,
		ADDRESS = EXT_ROW.ADDRESS,
		PHONE = EXT_ROW.PHONE,
		EMAIL = EXT_ROW.EMAIL,
		WEBSITE = EXT_ROW.WEBSITE
	WHERE CD = EXT_ROW.CODE;
	END IF;
		
END LOOP;
COMMIT;
END P_ETL_PUBLI;