CREATE OR REPLACE PROCEDURE P_ETL_AUTHOR AS
CURSOR EXT_CUR_AUTHOR IS 
SELECT * FROM T_EXT_AUTHOR;
EXT_ROW EXT_CUR_AUTHOR%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_AUTHOR LOOP

	INSERT INTO T_MT_AUTHOR 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.ADDRESS, 
		EXT_ROW.PHONE, 
		EXT_ROW.EMAIL,
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_AUTHOR;