CREATE OR REPLACE PROCEDURE P_ETL_BKTYPE AS
CURSOR EXT_CUR_BKTYPE IS 
SELECT EXTBKT.*, MTBKT.ID AS MTBKTID 
FROM T_EXT_BKTYPE EXTBKT
LEFT JOIN T_MT_BKTYPE MTBKT
ON EXTBKT.CODE = MTBKT.CD;

EXT_ROW EXT_CUR_BKTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_BKTYPE LOOP

	IF EXT_ROW.MTBKTID IS NULL THEN
	INSERT INTO T_MT_BKTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_BKTYPE
	SET NAME = EXT_ROW.NAME
	WHERE CD = EXT_ROW.CODE;
	END IF;
END LOOP;
COMMIT;
END P_ETL_BKTYPE;