CREATE OR REPLACE PROCEDURE P_ETL_PUBLI AS
CURSOR EXT_CUR_PUBLI IS 
SELECT * FROM T_EXT_PUBLI;
EXT_ROW EXT_CUR_PUBLI%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_PUBLI LOOP

	INSERT INTO T_MT_PUBLI 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.ADDRESS, 
		EXT_ROW.PHONE, 
		EXT_ROW.EMAIL,
		EXT_ROW.WEBSITE,
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_PUBLI;