CREATE OR REPLACE PROCEDURE P_ETL_TRANTYPE AS
CURSOR EXT_CUR_TRANTYPE IS 
SELECT EXTTRANT.*, MTTRANT.ID AS MTTRANTID 
FROM T_EXT_TRANTYPE EXTTRANT
LEFT JOIN T_MT_TRANTYPE MTTRANT
ON EXTTRANT.CODE = MTTRANT.CD;

EXT_ROW EXT_CUR_TRANTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_TRANTYPE LOOP

	IF EXT_ROW.MTTRANTID IS NULL THEN
	INSERT INTO T_MT_TRANTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME,
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_TRANTYPE
	SET NAME = EXT_ROW.NAME
	WHERE CD = EXT_ROW.CODE;
	END IF;
END LOOP;
COMMIT;
END P_ETL_TRANTYPE;