CREATE OR REPLACE PROCEDURE P_ETL_STTYPE AS
CURSOR EXT_CUR_STTYPE IS 
SELECT EXTSTT.*, MTSTT.ID AS MTSTTID 
FROM T_EXT_STTYPE EXTSTT
LEFT JOIN T_MT_STTYPE MTSTT
ON EXTSTT.CODE = MTSTT.CD;

EXT_ROW EXT_CUR_STTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_STTYPE LOOP

	IF EXT_ROW.MTSTTID IS NULL THEN
	INSERT INTO T_MT_STTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_STTYPE
	SET NAME = EXT_ROW.NAME
	WHERE CD = EXT_ROW.CODE;
	END IF;
	
END LOOP;
COMMIT;
END P_ETL_STTYPE;