CREATE OR REPLACE PROCEDURE P_ETL_SPTYPE AS
CURSOR EXT_CUR_SPTYPE IS 
SELECT EXTSPT.*, MTSPT.ID AS MTSPTID 
FROM T_EXT_SPTYPE EXTSPT
LEFT JOIN T_MT_SPTYPE MTSPT
ON EXTSPT.CODE = MTSPT.CD;

EXT_ROW EXT_CUR_SPTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_SPTYPE LOOP

	IF EXT_ROW.MTSPTID IS NULL THEN
	INSERT INTO T_MT_SPTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_SPTYPE
	SET NAME = EXT_ROW.NAME
	WHERE CD = EXT_ROW.CODE;
	END IF;
END LOOP;
COMMIT;
END P_ETL_SPTYPE;