CREATE OR REPLACE PROCEDURE P_ETL_ROLE AS
CURSOR EXT_CUR_ROLE IS
SELECT * FROM T_EXT_ROLE;
EXT_ROW EXT_CUR_ROLE%ROWTYPE;

BEGIN
FOR EXT_ROW IN EXT_CUR_ROLE LOOP
INSERT INTO T_MT_ROLE
VALUES 
(
SYS_GUID(),
EXT_ROW.ROLE,
EXT_ROW.CODE
);
END LOOP;
COMMIT;
END;