create or replace
PROCEDURE P_ETL_STATIO AS
CURSOR EXT_CUR_STATIO IS
SELECT extstatio.*, mtstatiotype.ID as TYPEID, mtstatio.ID as STATIOID
FROM T_EXT_STATIO extstatio
LEFT JOIN T_MT_STATIO mtstatio
ON extstatio.CODE = mtstatio.CD
LEFT JOIN T_MT_STTYPE mtstatiotype
ON extstatio.typecode = mtstatiotype.CD;
EXT_ROW EXT_CUR_STATIO%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_STATIO LOOP

	IF EXT_ROW.STATIOID IS NULL THEN
	INSERT INTO T_MT_STATIO
	VALUES
	(
		SYS_GUID(),
		EXT_ROW.NAME,
		EXT_ROW.TYPEID,
		EXT_ROW.PRICE,
		EXT_ROW.STOCK,
		EXT_ROW.CODE
	);
	ELSE
	UPDATE T_MT_STATIO
	SET NAME = EXT_ROW.NAME,
		TYPEID = EXT_ROW.TYPEID,
		PRICE = EXT_ROW.PRICE,
		STOCK = EXT_ROW.STOCK
	WHERE CD = EXT_ROW.CODE;
	END IF;
END LOOP;
COMMIT;
END P_ETL_STATIO;
