CREATE OR REPLACE PROCEDURE P_ETL_SPTYPE AS
CURSOR EXT_CUR_SPTYPE IS 
SELECT * FROM T_EXT_SPTYPE;
EXT_ROW EXT_CUR_SPTYPE%ROWTYPE;
BEGIN

FOR EXT_ROW IN EXT_CUR_SPTYPE LOOP

	INSERT INTO T_MT_SPTYPE 
	VALUES 
	(
		SYS_GUID(), 
		EXT_ROW.NAME, 
		EXT_ROW.CODE
	);
END LOOP;
COMMIT;
END P_ETL_SPTYPE;