create or replace 
PROCEDURE P_DELETE_EMPLOYEE(
IN_CD IN T_MT_EMPLOYEE.CD%TYPE
)
IS
EMPLOYEE_ID VARCHAR(32);

BEGIN
SELECT ID INTO EMPLOYEE_ID from T_MT_EMPLOYEE WHERE CD = IN_CD;

DELETE FROM T_MT_EMPLOYEE WHERE ID=EMPLOYEE_ID;

DELETE FROM T_MT_EMPLOYEE WHERE CD = IN_CD;

COMMIT;
END;