create or replace 
PROCEDURE P_DELETE_CUSTOMER(
IN_CD IN T_MT_CUSTOMER.CD%TYPE
)
IS
CUSTOMER_ID VARCHAR(32);

BEGIN
select ID INTO CUSTOMER_ID from T_MT_CUSTOMER WHERE CD = IN_CD;

DELETE FROM T_MT_CUSTOMER WHERE ID = CUSTOMER_ID;

DELETE FROM T_MT_CUSTOMER WHERE CD = IN_CD;

COMMIT;
END;