CREATE OR REPLACE PROCEDURE P_DELETE_BKTYPE(
IN_CD IN T_MT_BKTYPE.CD%TYPE
)
IS
BKTYPE_ID VARCHAR(32); 

BEGIN
select ID INTO BKTYPE_ID from T_MT_BKTYPE WHERE CD = IN_CD;

DELETE FROM T_MT_BOOK WHERE BOOKTYPE = BKTYPE_ID;

DELETE FROM T_MT_BKTYPE WHERE CD = IN_CD;

COMMIT;
END;