CREATE OR REPLACE PROCEDURE P_DELETE_AUTHOR(
IN_CD IN T_MT_AUTHOR.CD%TYPE
)
IS
AUTHOR_ID VARCHAR(32); 

BEGIN
select ID INTO AUTHOR_ID from T_MT_AUTHOR WHERE CD = IN_CD;

DELETE FROM T_MT_BOOK WHERE AUTHORID = AUTHOR_ID;

DELETE FROM T_MT_AUTHOR WHERE CD = IN_CD;

COMMIT;
END;
