CREATE OR REPLACE FUNCTION F_RET_SUPPLIER
RETURN SYS_REFCURSOR
IS
SUP_CUR SYS_REFCURSOR;
BEGIN

OPEN SUP_CUR FOR
SELECT 
S.CD,
S.NAME,
SPTYPE.NAME AS SUPPLIER_TYPE,
S.ADDRESS
FROM T_MT_SUPPLIER S
INNER JOIN T_MT_SPTYPE SPTYPE
ON S.SUPPID = SPTYPE.ID;

RETURN SUP_CUR;
END;