CREATE OR REPLACE FUNCTION F_RET_BOOK 
RETURN SYS_REFCURSOR
IS
BK_CUR SYS_REFCURSOR;
BEGIN

OPEN BK_CUR FOR
SELECT
BK.CD, 
BK.TITLE,
BK.DESCRIPTION,
ATH.NAME AS ATH_NAME,
PUB.NAME AS PUB_NAME,
BKTYPE.NAME AS BOOK_TYPE,
BK.PRICE,
BK.STOCK
FROM T_MT_BOOK BK 
INNER JOIN T_MT_BKTYPE BKTYPE
ON BK.BOOKTYPE = BKTYPE.ID
INNER JOIN T_MT_AUTHOR ATH
ON BK.AUTHORID = ATH.ID
INNER JOIN T_MT_PUBLI PUB
ON BK.PID = PUB.ID;

RETURN BK_CUR;
END;