CREATE OR REPLACE FUNCTION F_RET_TRANSACTION
RETURN SYS_REFCURSOR
IS
T_CUR SYS_REFCURSOR;
BEGIN

OPEN T_CUR FOR
SELECT 
T.CD,
C.NAME AS CUSTOMER_NAME,
E.NAME AS EMPLOYEE_NAME,
I.TITLE AS ITEM_TITLE,
D.TITLE AS DISCOUNT_NAME,
TTYPE.NAME AS TRANSACTION_TYPE,
T.DATE_COMMENCE AS TRANSACTION_DATE,
T.TOTAL_PAYMENT
FROM T_TRANSACTION T
INNER JOIN T_MT_CUSTOMER C
ON T.CUSTOMER_ID = C.ID
INNER JOIN T_MT_EMPLOYEE E
ON T.EMPLOYEE_ID = E.ID
INNER JOIN T_MT_ITEM I
ON T.ITEM_ID = I.ID
INNER JOIN T_MT_DISCOUNT D
ON T.DISCOUNT_ID = D.ID
INNER JOIN T_MT_TRANTYPE TTYPE
ON T.TRAN_ID = TTYPE.ID;

RETURN T_CUR;
END;