CREATE OR REPLACE PROCEDURE P_MONTH_REPORT (
	START_DATE IN VARCHAR2,
	END_DATE IN VARCHAR2,
	CUR_REPORT OUT SYS_REFCURSOR
)
IS
FIRST_DATE DATE;
LAST_DATE DATE;

BEGIN

FIRST_DATE := TO_DATE(START_DATE, 'DDMMYYYY');
LAST_DATE := TO_DATE(END_DATE, 'DDMMYYYY');

OPEN CUR_REPORT FOR
SELECT 
VW.EMP_CD,
VW.EMP_NAME,
SUM(VW.TOTAL_PAYMENT) AS TOTAL_PROFIT

FROM VW_SALES VW
WHERE VW.DATE_COMMENCE BETWEEN FIRST_DATE AND LAST_DATE
GROUP BY VW.EMP_CD, VW.EMP_NAME
ORDER BY VW.EMP_CD;

END;