CREATE OR REPLACE VIEW  VW_SALES AS
SELECT 
TRAN.ID,
TRAN.TOTAL_PAYMENT,
BK.CD AS BOOK_CD,
BK.TITLE AS BOOK_TITLE,
EMP.CD AS EMP_CD,
EMP.NAME AS EMP_NAME,
TRAN.DATE_COMMENCE
FROM T_TRANSACTION TRAN
INNER JOIN T_MT_BOOK BK
ON TRAN.BOOK_ID = BK.ID
INNER JOIN T_MT_EMPLOYEE EMP
ON TRAN.EMPLOYEE_ID = EMP.ID

