CREATE OR REPLACE PROCEDURE P_DELETE_ROLE(
IN_CD IN T_MT_ROLE.CD%TYPE
)
IS
ROLE_ID VARCHAR(32); 

BEGIN
select ID INTO ROLE_ID from T_MT_ROLE WHERE CD = IN_CD;

DELETE FROM T_MT_EMPLOYEE WHERE ROLE_ID = ROLE_ID;

DELETE FROM T_MT_ROLE WHERE CD = IN_CD;

COMMIT;
END;