CREATE OR REPLACE PROCEDURE P_DELETE_ITEM(
IN_CD IN T_MT_ITEM.CD%TYPE
)
IS
ITEM_ID VARCHAR(32); 

BEGIN
select ID INTO ITEM_ID from T_MT_ITEM WHERE CD = IN_CD;

DELETE FROM T_MT_ITEM WHERE CD = IN_CD;

COMMIT;
END;