CREATE OR REPLACE PROCEDURE P_DELETE_STTYPE(
IN_CD IN T_MT_STTYPE.CD%TYPE
)
IS
STTYPE_ID VARCHAR(32); 

BEGIN
select ID INTO STTYPE_ID from T_MT_STTYPE WHERE CD = IN_CD;

DELETE FROM T_MT_STATIO WHERE TYPEID = STTYPE_ID;

DELETE FROM T_MT_STTYPE WHERE CD = IN_CD;

COMMIT;
END;