create or replace
PROCEDURE P_ADD_BOOK(
				IN_TITLE IN T_MT_BOOK.TITLE%TYPE,
				IN_DESCRIPTION IN T_MT_BOOK.DESCRIPTION%TYPE,
				IN_AUTHORCD IN T_MT_AUTHOR.CD%TYPE,
				IN_PUBLICD IN T_MT_PUBLI.CD%TYPE,
				IN_BKTYPECD IN T_MT_BKTYPE.CD%TYPE,
				IN_PRICE IN T_MT_BOOK.PRICE%TYPE,
				IN_STOCK IN T_MT_BOOK.STOCK%TYPE,
				IN_ID IN T_MT_BOOK.CD%TYPE
)
IS
AUTHOR_ID VARCHAR(32);
PUBLI_ID VARCHAR(32);
BKTYPE_ID VARCHAR(32);
BEGIN

SELECT AUTHOR.ID INTO AUTHOR_ID FROM T_MT_AUTHOR AUTHOR WHERE AUTHOR.CD = IN_AUTHORCD;
SELECT PUBLISHER.ID INTO PUBLI_ID FROM T_MT_PUBLI PUBLISHER WHERE PUBLISHER.CD = IN_PUBLICD;
SELECT BOOKTYPE.ID INTO BKTYPE_ID FROM T_MT_BKTYPE BOOKTYPE WHERE BOOKTYPE.CD = IN_BKTYPECD;
INSERT INTO T_MT_BOOK
VALUES
(
		SYS_GUID(),
		IN_TITLE,
		IN_DESCRIPTION,
		AUTHOR_ID,
		PUBLI_ID,
		BKTYPE_ID,
		IN_PRICE,
		IN_STOCK,
		IN_ID
);

COMMIT;

END;
