create or replace
PROCEDURE P_ADD_STATIO(
				IN_NAME IN T_MT_STATIO.NAME%TYPE,
				IN_TYPECD IN T_MT_STTYPE.CD%TYPE,
				IN_PRICE IN T_MT_STATIO.PRICE%TYPE,
				IN_STOCK IN T_MT_STATIO.STOCK%TYPE,
				IN_CD IN T_MT_STATIO.CD%TYPE
)
IS
TYPE_ID VARCHAR(32);
BEGIN

SELECT STATIONERYTYPE.ID INTO TYPE_ID FROM T_MT_STTYPE STATIONERYTYPE WHERE STATIONERYTYPE.CD = IN_TYPECD;
INSERT INTO T_MT_STATIO
VALUES
(
		SYS_GUID(),
                IN_NAME,
		TYPE_ID,
		IN_PRICE,
		IN_STOCK,
		IN_CD
);

COMMIT;

END;
