CREATE OR REPLACE PROCEDURE P_ADD_DISCOUNT(
   IN_TIT IN T_MT_DISCOUNT.TITLE%TYPE,
   IN_DISC IN T_MT_DISCOUNT.DISCTYPE%TYPE,
   IN_AM IN T_MT_DISCOUNT.AMOUNT%TYPE,
   IN_DESC IN T_MT_DISCOUNT.DESCRIPTION%TYPE,
   IN_CD IN T_MT_DISCOUNT.CD%TYPE
)
IS


BEGIN

INSERT INTO T_MT_DISCOUNT
VALUES
( 
   SYS_GUID,
   IN_TIT,
   IN_DISC,
   IN_AM,
   IN_DESC,
   IN_CD
);

COMMIT;

END;