create or replace
PROCEDURE P_ADD_SUPPLIER(
				IN_NAME IN T_MT_SUPPLIER.NAME%TYPE,
				IN_SPTYPECD IN T_MT_SPTYPE.CD%TYPE,
				IN_ADDRESS IN T_MT_SUPPLIER.ADDRESS%TYPE,
				IN_ID IN T_MT_SUPPLIER.CD%TYPE
)
IS
SUPP_ID VARCHAR(32);
BEGIN

SELECT SUPPTYPE.ID INTO SUPP_ID FROM T_MT_SPTYPE SUPPTYPE WHERE SUPPTYPE.CD = IN_SPTYPECD;
INSERT INTO T_MT_SUPPLIER
VALUES
(
		SYS_GUID(),
		IN_NAME,
		SUPP_ID,
		IN_ADDRESS,
		IN_ID
);

COMMIT;

END;
