create or replace PROCEDURE P_UPDATE_BOOK (
		IN_TYPE IN VARCHAR2,
        IN_VALUE IN VARCHAR2,
        IN_CD IN T_MT_BOOK.CD%TYPE
)
IS
update_sql varchar2(225);
UPD_VALUE VARCHAR2(32);
BEGIN

IF UPPER(IN_TYPE) = 'AUTHORID' THEN
SELECT A.ID INTO UPD_VALUE FROM T_MT_AUTHOR A WHERE A.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'PID' THEN
SELECT P.ID INTO UPD_VALUE FROM T_MT_PUBLI P WHERE P.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'BOOKTYPE' THEN
SELECT B.ID INTO UPD_VALUE FROM T_MT_BKTYPE B WHERE B.CD = IN_VALUE;
ELSE
UPD_VALUE := IN_VALUE;
END IF;

update_sql :=  'UPDATE T_MT_BOOK SET ' || IN_TYPE  || 
                    '= :1 WHERE CD = :2' ;

execute immediate update_sql using UPD_VALUE,IN_CD;

END P_UPDATE_BOOK;
