create or replace PROCEDURE P_UPDATE_SUPPLIER (
		IN_TYPE IN VARCHAR2,
        IN_VALUE IN VARCHAR2,
        IN_CD IN T_MT_SUPPLIER.CD%TYPE
)
IS
update_sql varchar2(225);
UPD_VALUE VARCHAR2(32);
BEGIN

IF UPPER(IN_TYPE) = 'SUPPID' THEN
SELECT S.ID INTO UPD_VALUE FROM T_MT_SPTYPE S WHERE S.CD = IN_VALUE;
ELSE
UPD_VALUE := IN_VALUE;
END IF;

update_sql :=  'UPDATE T_MT_SUPPLIER SET ' || IN_TYPE  || 
                    '= :1 WHERE CD = :2' ;

execute immediate update_sql using UPD_VALUE,IN_CD;

END P_UPDATE_SUPPLIER;
