create or replace PROCEDURE P_UPDATE_EMPLOYEE (
		IN_TYPE IN VARCHAR2,
		IN_VALUE IN VARCHAR2,
        IN_CD IN T_MT_EMPLOYEE.CD%TYPE

)
IS
update_sql varchar2(225);
UPD_VALUE VARCHAR2(32);
BEGIN

IF UPPER(IN_TYPE) = 'ROLE_ID' THEN
SELECT R.ID INTO UPD_VALUE FROM T_MT_ROLE R WHERE R.CD = IN_VALUE;
ELSE
UPD_VALUE := IN_VALUE;
END IF;

update_sql :=  'UPDATE T_MT_EMPLOYEE SET ' || IN_TYPE  ||
                    '= :1 WHERE CD = :2' ;

execute immediate update_sql using UPD_VALUE,IN_CD;

END P_UPDATE_EMPLOYEE;
