create or replace PROCEDURE P_UPDATE_TRANSACTION (
		IN_TYPE IN VARCHAR2,
        IN_VALUE IN VARCHAR2,
        IN_CD IN T_TRANSACTION.CD%TYPE
)
IS
update_sql varchar2(225);
UPD_VALUE VARCHAR2(32);
BEGIN

IF UPPER(IN_TYPE) = 'CUSTOMER_ID' THEN
SELECT C.ID INTO UPD_VALUE FROM T_MT_CUSTOMER C WHERE C.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'EMPLOYEE_ID' THEN
SELECT E.ID INTO UPD_VALUE FROM T_MT_EMPLOYEE E WHERE E.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'ITEM_ID' THEN
SELECT I.ID INTO UPD_VALUE FROM T_MT_ITEM I WHERE I.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'DISCOUNT_ID' THEN
SELECT D.ID INTO UPD_VALUE FROM T_MT_DISCOUNT D WHERE D.CD = IN_VALUE;
ELSIF UPPER(IN_TYPE) = 'TRAN_ID' THEN
SELECT T.ID INTO UPD_VALUE FROM T_MT_TRANTYPE T WHERE T.CD = IN_VALUE;
ELSE
UPD_VALUE := IN_VALUE;
END IF;

update_sql :=  'UPDATE T_TRANSACTION SET ' || IN_TYPE  || 
                    '= :1 WHERE CD = :2' ;

execute immediate update_sql using UPD_VALUE,IN_CD;

END P_UPDATE_TRANSACTION;
